type = "javascript"
workers_dev = false

[dev]
ip = "0.0.0.0"
port = 9000
local_protocol="http"
upstream_protocol="https"

[env.preview]
name = "embedclout-preview"
workers_dev = true

[env.production]
name = "embedclout-prod"
workers_dev = false